name: compressed-size
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
          run_install: false

      - name: compressed-size-action
        uses: preactjs/compressed-size-action@v2
        with:
          pattern: "packages/**/dist/!(*.module|*.min).{js,mjs}"
          build-script: "ci:build"
          strip-hash: "[.-](\\w{8,9})\\.(?:js|css)$"
